import { Quiz } from '@/interfaces/Quiz';

const QuizMockData: Quiz[] = [
  {
    _id: '1',
    comments: [],
    channel: {
      _id: '1',
      name: 'mock channel',
      authRequired: false,
      description: 'this is mock channel',
      posts: ['post1', 'post2'],
      createdAt: Date.toString(),
      updatedAt: Date.toString(),
    },
    author: {
      _id: '1',
      role: 'common',
      isOnline: false,
      posts: [],
      likes: [],
      comments: [],
      notifications: [],
      fullName: 'fullName',
      email: 'email@email.com',
      createdAt: Date.toString(),
      updatedAt: Date.toString(),
    },
    question: '자바스크립트는 인터프리터 언어이다.',
    des: '자바스크립트는 인터프리터 언어입니다.',
    tag: ['Javascript', 'Frontend'],
    difficulty: 5,
    importance: 4,
    answerType: 'trueOrFalse',
    answer: 'true',
    createdAt: Date.toString(),
    updatedAt: Date.toString(),
  },
  {
    _id: '2',
    comments: [],
    channel: {
      _id: '1',
      name: 'mock channel',
      authRequired: false,
      description: 'this is mock channel',
      posts: ['post1', 'post2'],
      createdAt: Date.toString(),
      updatedAt: Date.toString(),
    },
    author: {
      _id: '1',
      role: 'common',
      isOnline: false,
      posts: [],
      likes: [],
      comments: [],
      notifications: [],
      fullName: 'fullName',
      email: 'email@email.com',
      createdAt: Date.toString(),
      updatedAt: Date.toString(),
    },
    question: '자바스크립트는 인터프리터 언어이다.',
    des: '자바스크립트는 인터프리터 언어입니다.',
    tag: ['Javascript', 'Frontend'],
    difficulty: 5,
    importance: 4,
    answerType: 'trueOrFalse',
    answer: 'true',
    createdAt: Date.toString(),
    updatedAt: Date.toString(),
  },
  {
    _id: '3',
    comments: [],
    channel: {
      _id: '1',
      name: 'mock channel',
      authRequired: false,
      description: 'this is mock channel',
      posts: ['post1', 'post2'],
      createdAt: Date.toString(),
      updatedAt: Date.toString(),
    },
    author: {
      _id: '1',
      role: 'common',
      isOnline: false,
      posts: [],
      likes: [],
      comments: [],
      notifications: [],
      fullName: 'fullName',
      email: 'email@email.com',
      createdAt: Date.toString(),
      updatedAt: Date.toString(),
    },
    question: '자바스크립트는 인터프리터 언어이다.',
    des: '자바스크립트는 인터프리터 언어입니다.',
    tag: ['Javascript', 'Frontend'],
    difficulty: 5,
    importance: 4,
    answerType: 'trueOrFalse',
    answer: 'true',
    createdAt: Date.toString(),
    updatedAt: Date.toString(),
  },
  {
    _id: '4',
    comments: [],
    channel: {
      _id: '1',
      name: 'mock channel',
      authRequired: false,
      description: 'this is mock channel',
      posts: ['post1', 'post2'],
      createdAt: Date.toString(),
      updatedAt: Date.toString(),
    },
    author: {
      _id: '1',
      role: 'common',
      isOnline: false,
      posts: [],
      likes: [],
      comments: [],
      notifications: [],
      fullName: 'fullName',
      email: 'email@email.com',
      createdAt: Date.toString(),
      updatedAt: Date.toString(),
    },
    question: '자바스크립트는 인터프리터 언어이다.',
    des: '자바스크립트는 인터프리터 언어입니다.',
    tag: ['Javascript', 'Frontend'],
    difficulty: 5,
    importance: 4,
    answerType: 'trueOrFalse',
    answer: 'true',
    createdAt: Date.toString(),
    updatedAt: Date.toString(),
  },
  {
    _id: '5',
    comments: [],
    channel: {
      _id: '1',
      name: 'mock channel',
      authRequired: false,
      description: 'this is mock channel',
      posts: ['post1', 'post2'],
      createdAt: Date.toString(),
      updatedAt: Date.toString(),
    },
    author: {
      _id: '1',
      role: 'common',
      isOnline: false,
      posts: [],
      likes: [],
      comments: [],
      notifications: [],
      fullName: 'fullName',
      email: 'email@email.com',
      createdAt: Date.toString(),
      updatedAt: Date.toString(),
    },
    question: '자바스크립트는 인터프리터 언어이다.',
    des: '자바스크립트는 인터프리터 언어입니다.',
    tag: ['Javascript', 'Frontend'],
    difficulty: 5,
    importance: 4,
    answerType: 'trueOrFalse',
    answer: 'true',
    createdAt: Date.toString(),
    updatedAt: Date.toString(),
  },
  {
    _id: '6',
    comments: [],
    channel: {
      _id: '1',
      name: 'mock channel',
      authRequired: false,
      description: 'this is mock channel',
      posts: ['post1', 'post2'],
      createdAt: Date.toString(),
      updatedAt: Date.toString(),
    },
    author: {
      _id: '1',
      role: 'common',
      isOnline: false,
      posts: [],
      likes: [],
      comments: [],
      notifications: [],
      fullName: 'fullName',
      email: 'email@email.com',
      createdAt: Date.toString(),
      updatedAt: Date.toString(),
    },
    question: '자바스크립트는 인터프리터 언어이다.',
    des: '자바스크립트는 인터프리터 언어입니다.',
    tag: ['Javascript', 'Frontend'],
    difficulty: 5,
    importance: 4,
    answerType: 'trueOrFalse',
    answer: 'true',
    createdAt: Date.toString(),
    updatedAt: Date.toString(),
  },
];

export default QuizMockData;
