import type { Quiz } from '@/interfaces/Quiz';

const QuizMockData: Quiz[] = [
  {
    _id: '1',
    likes: [],
    comments: [
      {
        _id: 'comment_1',
        comment: '최고에요!',
        author: {
          _id: '17',
          role: 'common',
          isOnline: false,
          posts: [],
          likes: [],
          comments: [],
          notifications: [],
          fullName: 'test1234',
          username: '',
          email: 'email@email.com',
          createdAt: new Date().toUTCString(),
          updatedAt: new Date().toUTCString(),
          following: [],
          messages: [],
        },
        post: '1',
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
      },
      {
        _id: 'comment_2',
        comment: '최고에요!2',
        author: {
          _id: '17',
          role: 'common',
          isOnline: false,
          posts: [],
          likes: [],
          comments: [],
          notifications: [],
          fullName: 'test1234',
          username: '',
          email: 'email@email.com',
          createdAt: new Date().toUTCString(),
          updatedAt: new Date().toUTCString(),
          following: [],
          messages: [],
        },
        post: '1',
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
      },
    ],
    channel: {
      _id: '1',
      name: 'mock channel',
      authRequired: false,
      description: 'this is mock channel',
      posts: ['post1', 'post2'],
      createdAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
    },
    author: {
      _id: '1',
      role: 'common',
      isOnline: false,
      posts: [],
      likes: [],
      comments: [],
      notifications: [],
      fullName: 'fullName',
      username: '',
      email: 'email@email.com',
      createdAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
      following: [],
      messages: [],
    },
    question: '자바스크립트는 인터프리터 언어이다.',
    answerDescription: '자바스크립트는 인터프리터 언어입니다.',
    category: 'Javascript',
    difficulty: 5,
    importance: 4,
    answerType: 'trueOrFalse',
    answer: 'true',
    createdAt: new Date().toUTCString(),
    updatedAt: new Date().toUTCString(),
  },
  {
    _id: '2',
    likes: [],
    comments: [
      {
        _id: 'comment_3',
        comment: '최고에요!',
        author: {
          _id: '17',
          role: 'common',
          isOnline: false,
          posts: [],
          likes: [],
          comments: [],
          notifications: [],
          fullName: 'test1234',
          username: '',
          email: 'email@email.com',
          createdAt: new Date().toUTCString(),
          updatedAt: new Date().toUTCString(),
          following: [],
          messages: [],
        },
        post: '2',
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
      },
      {
        _id: 'comment_4',
        comment: '최고에요!2',
        author: {
          _id: '17',
          role: 'common',
          isOnline: false,
          posts: [],
          likes: [],
          comments: [],
          notifications: [],
          fullName: 'test1234',
          username: '',
          email: 'email@email.com',
          createdAt: new Date().toUTCString(),
          updatedAt: new Date().toUTCString(),
          following: [],
          messages: [],
        },
        post: '2',
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
      },
    ],
    channel: {
      _id: '1',
      name: 'mock channel',
      authRequired: false,
      description: 'this is mock channel',
      posts: ['post1', 'post2'],
      createdAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
    },
    author: {
      _id: '1',
      role: 'common',
      isOnline: false,
      posts: [],
      likes: [],
      comments: [],
      notifications: [],
      fullName: 'fullName',
      username: '',
      email: 'email@email.com',
      createdAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
      following: [],
      messages: [],
    },
    question: '자바스크립트는 인터프리터 언어이다.',
    answerDescription: '자바스크립트는 인터프리터 언어입니다.',
    category: 'Javascript',
    difficulty: 5,
    importance: 4,
    answerType: 'trueOrFalse',
    answer: 'true',
    createdAt: new Date().toUTCString(),
    updatedAt: new Date().toUTCString(),
  },
  {
    _id: '3',
    likes: [],
    comments: [
      {
        _id: 'comment_5',
        comment: '최고에요!',
        author: {
          _id: '17',
          role: 'common',
          isOnline: false,
          posts: [],
          likes: [],
          comments: [],
          notifications: [],
          fullName: 'test1234',
          username: '',
          email: 'email@email.com',
          createdAt: new Date().toUTCString(),
          updatedAt: new Date().toUTCString(),
          following: [],
          messages: [],
        },
        post: '3',
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
      },
      {
        _id: 'comment_6',
        comment: '최고에요!2',
        author: {
          _id: '17',
          role: 'common',
          isOnline: false,
          posts: [],
          likes: [],
          comments: [],
          notifications: [],
          fullName: 'test1234',
          username: '',
          email: 'email@email.com',
          createdAt: new Date().toUTCString(),
          updatedAt: new Date().toUTCString(),
          following: [],
          messages: [],
        },
        post: '3',
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
      },
    ],
    channel: {
      _id: '1',
      name: 'mock channel',
      authRequired: false,
      description: 'this is mock channel',
      posts: ['post1', 'post2'],
      createdAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
    },
    author: {
      _id: '1',
      role: 'common',
      isOnline: false,
      posts: [],
      likes: [],
      comments: [],
      notifications: [],
      fullName: 'fullName',
      username: '',
      email: 'email@email.com',
      createdAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
      following: [],
      messages: [],
    },
    question: '자바스크립트는 인터프리터 언어이다.',
    answerDescription: '자바스크립트는 인터프리터 언어입니다.',
    category: 'Javascript',
    difficulty: 5,
    importance: 4,
    answerType: 'trueOrFalse',
    answer: 'true',
    createdAt: new Date().toUTCString(),
    updatedAt: new Date().toUTCString(),
  },
  {
    _id: '4',
    likes: [],
    comments: [
      {
        _id: 'comment_7',
        comment: '최고에요!',
        author: {
          _id: '17',
          role: 'common',
          isOnline: false,
          posts: [],
          likes: [],
          comments: [],
          notifications: [],
          fullName: 'test1234',
          username: '',
          email: 'email@email.com',
          createdAt: new Date().toUTCString(),
          updatedAt: new Date().toUTCString(),
          following: [],
          messages: [],
        },
        post: '4',
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
      },
      {
        _id: 'comment_8',
        comment: '최고에요!2',
        author: {
          _id: '17',
          role: 'common',
          isOnline: false,
          posts: [],
          likes: [],
          comments: [],
          notifications: [],
          fullName: 'test1234',
          username: '',
          email: 'email@email.com',
          createdAt: new Date().toUTCString(),
          updatedAt: new Date().toUTCString(),
          following: [],
          messages: [],
        },
        post: '4',
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
      },
    ],
    channel: {
      _id: '1',
      name: 'mock channel',
      authRequired: false,
      description: 'this is mock channel',
      posts: ['post1', 'post2'],
      createdAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
    },
    author: {
      _id: '1',
      role: 'common',
      isOnline: false,
      posts: [],
      likes: [],
      comments: [],
      notifications: [],
      fullName: 'fullName',
      username: '',
      email: 'email@email.com',
      createdAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
      following: [],
      messages: [],
    },
    question: '자바스크립트는 인터프리터 언어이다.',
    answerDescription: '자바스크립트는 인터프리터 언어입니다.',
    category: 'Javascript',
    difficulty: 5,
    importance: 4,
    answerType: 'trueOrFalse',
    answer: 'true',
    createdAt: new Date().toUTCString(),
    updatedAt: new Date().toUTCString(),
  },
  {
    _id: '5',
    likes: [],
    comments: [
      {
        _id: 'comment_9',
        comment: '최고에요!',
        author: {
          _id: '17',
          role: 'common',
          isOnline: false,
          posts: [],
          likes: [],
          comments: [],
          notifications: [],
          fullName: 'test1234',
          username: '',
          email: 'email@email.com',
          createdAt: new Date().toUTCString(),
          updatedAt: new Date().toUTCString(),
          following: [],
          messages: [],
        },
        post: '5',
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
      },
      {
        _id: 'comment_10',
        comment: '최고에요!2',
        author: {
          _id: '17',
          role: 'common',
          isOnline: false,
          posts: [],
          likes: [],
          comments: [],
          notifications: [],
          fullName: 'test1234',
          username: '',
          email: 'email@email.com',
          createdAt: new Date().toUTCString(),
          updatedAt: new Date().toUTCString(),
          following: [],
          messages: [],
        },
        post: '5',
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
      },
    ],
    channel: {
      _id: '1',
      name: 'mock channel',
      authRequired: false,
      description: 'this is mock channel',
      posts: ['post1', 'post2'],
      createdAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
    },
    author: {
      _id: '1',
      role: 'common',
      isOnline: false,
      posts: [],
      likes: [],
      comments: [],
      notifications: [],
      fullName: 'fullName',
      username: '',
      email: 'email@email.com',
      createdAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
      following: [],
      messages: [],
    },
    question: '자바스크립트는 인터프리터 언어이다.',
    answerDescription: '자바스크립트는 인터프리터 언어입니다.',
    category: 'Javascript',
    difficulty: 5,
    importance: 4,
    answerType: 'trueOrFalse',
    answer: 'true',
    createdAt: new Date().toUTCString(),
    updatedAt: new Date().toUTCString(),
  },
  {
    _id: '6',
    likes: [],
    comments: [
      {
        _id: 'comment_11',
        comment: '최고에요!',
        author: {
          _id: '17',
          role: 'common',
          isOnline: false,
          posts: [],
          likes: [],
          comments: [],
          notifications: [],
          fullName: 'test1234',
          username: '',
          email: 'email@email.com',
          createdAt: new Date().toUTCString(),
          updatedAt: new Date().toUTCString(),
          following: [],
          messages: [],
        },
        post: '6',
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
      },
      {
        _id: 'comment_12',
        comment: '최고에요!2',
        author: {
          _id: '17',
          role: 'common',
          isOnline: false,
          posts: [],
          likes: [],
          comments: [],
          notifications: [],
          fullName: 'test1234',
          username: '',
          email: 'email@email.com',
          createdAt: new Date().toUTCString(),
          updatedAt: new Date().toUTCString(),
          following: [],
          messages: [],
        },
        post: '6',
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
      },
    ],
    channel: {
      _id: '1',
      name: 'mock channel',
      authRequired: false,
      description: 'this is mock channel',
      posts: ['post1', 'post2'],
      createdAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
    },
    author: {
      _id: '1',
      role: 'common',
      isOnline: false,
      posts: [],
      likes: [],
      comments: [],
      notifications: [],
      fullName: 'fullName',
      username: '',
      email: 'email@email.com',
      createdAt: new Date().toUTCString(),
      updatedAt: new Date().toUTCString(),
      following: [],
      messages: [],
    },
    question: '자바스크립트는 인터프리터 언어이다.',
    answerDescription: '자바스크립트는 인터프리터 언어입니다.',
    category: 'Javascript',
    difficulty: 5,
    importance: 4,
    answerType: 'trueOrFalse',
    answer: 'true',
    createdAt: new Date().toUTCString(),
    updatedAt: new Date().toUTCString(),
  },
];

export default QuizMockData;
