import { UserAPI } from '@/interfaces/UserAPI';

const date = new Date();

const time = `${date.getHours()} : ${date.getMinutes()} : ${date.getSeconds()}`;

const RankingMockData: UserAPI[] = [
  {
    coverImage: '',
    image: '',
    _id: 'userA',
    role: 'user',
    isOnline: true,
    posts: [
      {
        likes: [
          {
            _id: 'v3r1f',
            user: 'sample123',
            post: '1v44cdc',
            createdAt: time,
            updatedAt: time,
          },
        ],
        _id: 'ascdre123',
        image: undefined,
        imagePublicId: undefined,
        title: JSON.stringify({
          question: '문제질문입니다?',
          des: '문제해설입니다!',
          tag: 'HTML',
          creator: 'UserAPI',
          difficulty: 5,
          importance: 10,
          answerType: 't/f',
          answer: 'true',
        }),
        channel: {
          _id: '12345',
          name: 'testChannel',
          authRequired: false,
          description: '테스트 채널',
          posts: ['테스트임'],
          createdAt: time,
          updatedAt: time,
        },
        author: {
          coverImage: '',
          image: '',
          emailVerified: undefined,
          banned: undefined,
          _id: '12312dcaca',
          role: 'tester',
          isOnline: true,
          posts: [],
          likes: [],
          comments: [],
          followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
          following: [],
          messages: [],
          notifications: [],
          fullName: '풀네임!',
          email: '이메일임',
          createdAt: time,
          updatedAt: time,
          username: '유저이름',
        },
        createdAt: time,
        updatedAt: time,
        comments: [],
      },
    ],
    likes: [
      {
        _id: 'v3r1f',
        user: 'sample123',
        post: '1v44cdc',
        createdAt: time,
        updatedAt: time,
      },
    ],
    comments: [
      {
        _id: 'v3r1f',
        comment: '이것은 코맨트!!',
        author: {
          coverImage: '',
          image: '',
          emailVerified: undefined,
          banned: undefined,
          _id: '12312dcaca',
          role: 'tester',
          isOnline: true,
          posts: [],
          likes: [],
          comments: [],
          followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
          following: [],
          messages: [],
          notifications: [],
          fullName: '풀네임!',
          email: '이메일임',
          createdAt: time,
          updatedAt: time,
          username: '유저이름',
        },
        post: '포스트아이디',
        createdAt: time,
        updatedAt: time,
      },
    ],
    notifications: [],
    fullName: 'A',
    username: JSON.stringify({
      totalPoints: 100000,
    }),
    email: 'testA@naver.com',
    createdAt: time,
    updatedAt: time,
    followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
    following: [],
    messages: [],
  },
  {
    coverImage: '',
    image: '',
    _id: 'userB',
    role: 'user',
    isOnline: true,
    posts: [
      {
        likes: [
          {
            _id: 'v3r1f',
            user: 'sample123',
            post: '1v44cdc',
            createdAt: time,
            updatedAt: time,
          },
        ],
        _id: 'ascdre123',
        image: undefined,
        imagePublicId: undefined,
        title: JSON.stringify({
          question: '문제질문입니다?',
          des: '문제해설입니다!',
          tag: 'React',
          creator: 'UserAPI',
          difficulty: 5,
          importance: 10,
          answerType: 't/f',
          answer: 'true',
        }),
        channel: {
          _id: '12345',
          name: 'testChannel',
          authRequired: false,
          description: '테스트 채널',
          posts: ['테스트임'],
          createdAt: time,
          updatedAt: time,
        },
        author: {
          coverImage: '',
          image: '',
          emailVerified: undefined,
          banned: undefined,
          _id: '12312dcaca',
          role: 'tester',
          isOnline: true,
          posts: [],
          likes: [],
          comments: [],
          followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
          following: [],
          messages: [],
          notifications: [],
          fullName: '풀네임!',
          email: '이메일임',
          createdAt: time,
          updatedAt: time,
          username: '유저이름',
        },
        createdAt: time,
        updatedAt: time,
        comments: [],
      },
    ],
    likes: [
      {
        _id: 'v3r1f',
        user: 'sample123',
        post: '1v44cdc',
        createdAt: time,
        updatedAt: time,
      },
    ],
    comments: [
      {
        _id: 'v3r1f',
        comment: '이것은 코맨트!!',
        author: {
          coverImage: '',
          image: '',
          emailVerified: undefined,
          banned: undefined,
          _id: '12312dcaca',
          role: 'tester',
          isOnline: true,
          posts: [],
          likes: [],
          comments: [],
          followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
          following: [],
          messages: [],
          notifications: [],
          fullName: '풀네임!',
          email: '이메일임',
          createdAt: time,
          updatedAt: time,
          username: '유저이름',
        },
        post: '포스트아이디',
        createdAt: time,
        updatedAt: time,
      },
    ],
    notifications: [],
    fullName: 'B',
    username: JSON.stringify({
      totalPoints: 65400,
    }),
    email: 'testB@naver.com',
    createdAt: time,
    updatedAt: time,
    followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
    following: [],
    messages: [],
  },
  {
    coverImage: '',
    image: '',
    _id: 'userC',
    role: 'user',
    isOnline: true,
    posts: [
      {
        likes: [
          {
            _id: 'v3r1f',
            user: 'sample123',
            post: '1v44cdc',
            createdAt: time,
            updatedAt: time,
          },
        ],
        _id: 'ascdre123',
        image: undefined,
        imagePublicId: undefined,
        title: JSON.stringify({
          question: '문제질문입니다?',
          des: '문제해설입니다!',
          tag: 'Javascript',
          creator: 'UserAPI',
          difficulty: 5,
          importance: 10,
          answerType: 't/f',
          answer: 'true',
        }),
        channel: {
          _id: '12345',
          name: 'testChannel',
          authRequired: false,
          description: '테스트 채널',
          posts: ['테스트임'],
          createdAt: time,
          updatedAt: time,
        },
        author: {
          coverImage: '',
          image: '',
          emailVerified: undefined,
          banned: undefined,
          _id: '12312dcaca',
          role: 'tester',
          isOnline: true,
          posts: [],
          likes: [],
          comments: [],
          followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
          following: [],
          messages: [],
          notifications: [],
          fullName: '풀네임!',
          email: '이메일임',
          createdAt: time,
          updatedAt: time,
          username: '유저이름',
        },
        createdAt: time,
        updatedAt: time,
        comments: [],
      },
    ],
    likes: [
      {
        _id: 'v3r1f',
        user: 'sample123',
        post: '1v44cdc',
        createdAt: time,
        updatedAt: time,
      },
    ],
    comments: [
      {
        _id: 'v3r1f',
        comment: '이것은 코맨트!!',
        author: {
          coverImage: '',
          image: '',
          emailVerified: undefined,
          banned: undefined,
          _id: '12312dcaca',
          role: 'tester',
          isOnline: true,
          posts: [],
          likes: [],
          comments: [],
          followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
          following: [],
          messages: [],
          notifications: [],
          fullName: '풀네임!',
          email: '이메일임',
          createdAt: time,
          updatedAt: time,
          username: '유저이름',
        },
        post: '포스트아이디',
        createdAt: time,
        updatedAt: time,
      },
    ],
    notifications: [],
    fullName: 'C',
    username: JSON.stringify({
      totalPoints: 23000,
    }),
    email: 'testC@naver.com',
    createdAt: time,
    updatedAt: time,
    followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
    following: [],
    messages: [],
  },
  {
    coverImage: '',
    image: '',
    _id: 'userD',
    role: 'user',
    isOnline: true,
    posts: [
      {
        likes: [
          {
            _id: 'v3r1f',
            user: 'sample123',
            post: '1v44cdc',
            createdAt: time,
            updatedAt: time,
          },
        ],
        _id: 'ascdre123',
        image: undefined,
        imagePublicId: undefined,
        title: JSON.stringify({
          question: '문제질문입니다?',
          des: '문제해설입니다!',
          tag: 'Vue',
          creator: 'UserAPI',
          difficulty: 5,
          importance: 10,
          answerType: 't/f',
          answer: 'true',
        }),
        channel: {
          _id: '12345',
          name: 'testChannel',
          authRequired: false,
          description: '테스트 채널',
          posts: ['테스트임'],
          createdAt: time,
          updatedAt: time,
        },
        author: {
          coverImage: '',
          image: '',
          emailVerified: undefined,
          banned: undefined,
          _id: '12312dcaca',
          role: 'tester',
          isOnline: true,
          posts: [],
          likes: [],
          comments: [],
          followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
          following: [],
          messages: [],
          notifications: [],
          fullName: '풀네임!',
          email: '이메일임',
          createdAt: time,
          updatedAt: time,
          username: '유저이름',
        },
        createdAt: time,
        updatedAt: time,
        comments: [],
      },
    ],
    likes: [
      {
        _id: 'v3r1f',
        user: 'sample123',
        post: '1v44cdc',
        createdAt: time,
        updatedAt: time,
      },
    ],
    comments: [
      {
        _id: 'v3r1f',
        comment: '이것은 코맨트!!',
        author: {
          coverImage: '',
          image: '',
          emailVerified: undefined,
          banned: undefined,
          _id: '12312dcaca',
          role: 'tester',
          isOnline: true,
          posts: [],
          likes: [],
          comments: [],
          followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
          following: [],
          messages: [],
          notifications: [],
          fullName: '풀네임!',
          email: '이메일임',
          createdAt: time,
          updatedAt: time,
          username: '유저이름',
        },
        post: '포스트아이디',
        createdAt: time,
        updatedAt: time,
      },
    ],
    notifications: [],
    fullName: 'D',
    username: JSON.stringify({
      totalPoints: 780000,
    }),
    email: 'testD@naver.com',
    createdAt: time,
    updatedAt: time,
    followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
    following: [],
    messages: [],
  },
  {
    coverImage: '',
    image: '',
    _id: 'userE',
    role: 'user',
    isOnline: true,
    posts: [
      {
        likes: [
          {
            _id: 'v3r1f',
            user: 'sample123',
            post: '1v44cdc',
            createdAt: time,
            updatedAt: time,
          },
        ],
        _id: 'ascdre123',
        image: undefined,
        imagePublicId: undefined,
        title: JSON.stringify({
          question: '문제질문입니다?',
          des: '문제해설입니다!',
          tag: 'SCSS',
          creator: 'UserAPI',
          difficulty: 5,
          importance: 10,
          answerType: 't/f',
          answer: 'true',
        }),
        channel: {
          _id: '12345',
          name: 'testChannel',
          authRequired: false,
          description: '테스트 채널',
          posts: ['테스트임'],
          createdAt: time,
          updatedAt: time,
        },
        author: {
          coverImage: '',
          image: '',
          emailVerified: undefined,
          banned: undefined,
          _id: '12312dcaca',
          role: 'tester',
          isOnline: true,
          posts: [],
          likes: [],
          comments: [],
          followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
          following: [],
          messages: [],
          notifications: [],
          fullName: '풀네임!',
          email: '이메일임',
          createdAt: time,
          updatedAt: time,
          username: '유저이름',
        },
        createdAt: time,
        updatedAt: time,
        comments: [],
      },
    ],
    likes: [
      {
        _id: 'v3r1f',
        user: 'sample123',
        post: '1v44cdc',
        createdAt: time,
        updatedAt: time,
      },
    ],
    comments: [
      {
        _id: 'v3r1f',
        comment: '이것은 코맨트!!',
        author: {
          coverImage: '',
          image: '',
          emailVerified: undefined,
          banned: undefined,
          _id: '12312dcaca',
          role: 'tester',
          isOnline: true,
          posts: [],
          likes: [],
          comments: [],
          followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
          following: [],
          messages: [],
          notifications: [],
          fullName: '풀네임!',
          email: '이메일임',
          createdAt: time,
          updatedAt: time,
          username: '유저이름',
        },
        post: '포스트아이디',
        createdAt: time,
        updatedAt: time,
      },
    ],
    notifications: [],
    fullName: 'E',
    username: JSON.stringify({
      totalPoints: 90000,
    }),
    email: 'testE@naver.com',
    createdAt: time,
    updatedAt: time,
    followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
    following: [],
    messages: [],
  },
  {
    coverImage: '',
    image: '',
    _id: 'userF',
    role: 'user',
    isOnline: true,
    posts: [
      {
        likes: [
          {
            _id: 'v3r1f',
            user: 'sample123',
            post: '1v44cdc',
            createdAt: time,
            updatedAt: time,
          },
        ],
        _id: 'ascdre123',
        image: undefined,
        imagePublicId: undefined,
        title: JSON.stringify({
          question: '문제질문입니다?',
          des: '문제해설입니다!',
          tag: '',
          creator: 'UserAPI',
          difficulty: 5,
          importance: 10,
          answerType: 't/f',
          answer: 'true',
        }),
        channel: {
          _id: '12345',
          name: 'testChannel',
          authRequired: false,
          description: '테스트 채널',
          posts: ['테스트임'],
          createdAt: time,
          updatedAt: time,
        },
        author: {
          coverImage: '',
          image: '',
          emailVerified: undefined,
          banned: undefined,
          _id: '12312dcaca',
          role: 'tester',
          isOnline: true,
          posts: [],
          likes: [],
          comments: [],
          followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
          following: [],
          messages: [],
          notifications: [],
          fullName: '풀네임!',
          email: '이메일임',
          createdAt: time,
          updatedAt: time,
          username: '유저이름',
        },
        createdAt: time,
        updatedAt: time,
        comments: [],
      },
    ],
    likes: [
      {
        _id: 'v3r1f',
        user: 'sample123',
        post: '1v44cdc',
        createdAt: time,
        updatedAt: time,
      },
    ],
    comments: [
      {
        _id: 'v3r1f',
        comment: '이것은 코맨트!!',
        author: {
          coverImage: '',
          image: '',
          emailVerified: undefined,
          banned: undefined,
          _id: '12312dcaca',
          role: 'tester',
          isOnline: true,
          posts: [],
          likes: [],
          comments: [],
          followers: ['팔로워1', '팔로워2', '팔로워3', '팔로워4', '팔로워5'],
          following: [],
          messages: [],
          notifications: [],
          fullName: '풀네임!',
          email: '이메일임',
          createdAt: time,
          updatedAt: time,
          username: '유저이름',
        },
        post: '포스트아이디',
        createdAt: time,
        updatedAt: time,
      },
    ],
    notifications: [],
    fullName: 'F',
    username: JSON.stringify({
      totalPoints: 0,
    }),
    email: 'testF@naver.com',
    createdAt: time,
    updatedAt: time,
    followers: [],
    following: [],
    messages: [],
  },
];

export default RankingMockData;
