import type { UserAPI } from '@/interfaces/UserAPI';

const RankingMockData: UserAPI[] = [
  {
    _id: 'user01',
    role: 'Regular',
    isOnline: true,
    posts: [],
    likes: [],
    comments: [],
    notifications: [],
    fullName: 'Apple',
    username: JSON.stringify({
      totalPoints: 0,
    }),
    email: 'test@naver.com',
    createdAt: Date.now().toString(),
    updatedAt: Date.now().toString(),
    messages: [],
    following: [],
  },
  {
    _id: 'user02',
    role: 'Regular',
    isOnline: true,
    posts: [],
    likes: ['1'],
    comments: [],
    notifications: [],
    fullName: 'Banana',
    username: JSON.stringify({
      totalPoints: 1000,
    }),
    email: 'test@naver.com',
    createdAt: Date.now().toString(),
    updatedAt: Date.now().toString(),
    messages: [],
    following: [],
  },
  {
    _id: 'user03',
    role: 'Regular',
    isOnline: true,
    posts: [],
    likes: [],
    comments: ['1', '1'],
    notifications: [],
    fullName: 'Candle',
    username: JSON.stringify({
      totalPoints: 5000,
    }),
    email: 'test@naver.com',
    createdAt: Date.now().toString(),
    updatedAt: Date.now().toString(),
    messages: [],
    following: [],
  },
  {
    _id: 'user04',
    role: 'Regular',
    isOnline: true,
    posts: [],
    likes: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
    comments: ['1', '1'],
    notifications: [],
    fullName: 'Dollar',
    username: JSON.stringify({
      totalPoints: 10000,
    }),
    email: 'test@naver.com',
    createdAt: Date.now().toString(),
    updatedAt: Date.now().toString(),
    messages: [],
    following: [],
  },
  {
    _id: 'user05',
    role: 'Regular',
    isOnline: true,
    posts: [],
    likes: ['1', '1'],
    comments: ['1', '1'],
    notifications: [],
    fullName: 'Edison',
    username: JSON.stringify({
      totalPoints: 50000,
    }),
    email: 'test@naver.com',
    createdAt: Date.now().toString(),
    updatedAt: Date.now().toString(),
    messages: [],
    following: [],
  },
  {
    _id: 'user06',
    role: 'Regular',
    isOnline: true,
    posts: [],
    likes: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
    comments: ['1', '1'],
    notifications: [],
    fullName: 'Fries',
    username: JSON.stringify({
      totalPoints: 100000,
    }),
    email: 'test@naver.com',
    createdAt: Date.now().toString(),
    updatedAt: Date.now().toString(),
    messages: [],
    following: [],
  },
  {
    _id: 'user07',
    role: 'Regular',
    isOnline: true,
    posts: [],
    likes: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
    comments: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
    notifications: [],
    fullName: 'Galaxy',
    username: JSON.stringify({
      totalPoints: 500000,
    }),
    email: 'test@naver.com',
    createdAt: Date.now().toString(),
    updatedAt: Date.now().toString(),
    messages: [],
    following: [],
  },
  {
    _id: 'user08',
    role: 'Regular',
    isOnline: true,
    posts: [],
    likes: ['1', '1', '1'],
    comments: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
    notifications: [],
    fullName: 'History',
    username: JSON.stringify({
      totalPoints: 1000000,
    }),
    email: 'test@naver.com',
    createdAt: Date.now().toString(),
    updatedAt: Date.now().toString(),
    messages: [],
    following: [],
  },
  {
    _id: 'user09',
    role: 'Regular',
    isOnline: true,
    posts: [],
    likes: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
    comments: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
    notifications: [],
    fullName: 'Iron',
    username: JSON.stringify({
      totalPoints: 5000000,
    }),
    email: 'test@naver.com',
    createdAt: Date.now().toString(),
    updatedAt: Date.now().toString(),
    messages: [],
    following: [],
  },
];

export default RankingMockData;
